// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALCe_6Isui2UfBTjGEwkzWdosHQcX_2Ls',
    appId: '1:906357683460:web:322f6ea3cc90d2169c0c51',
    messagingSenderId: '906357683460',
    projectId: 'road-companion-700b0',
    authDomain: 'road-companion-700b0.firebaseapp.com',
    storageBucket: 'road-companion-700b0.firebasestorage.app',
    measurementId: 'G-5JM32GHF7P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDh5SOOyWSl_ENOMGJxxcZU7u-dEhdI3Kk',
    appId: '1:906357683460:android:a5171ee1e16842949c0c51',
    messagingSenderId: '906357683460',
    projectId: 'road-companion-700b0',
    storageBucket: 'road-companion-700b0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSDmBtqhitWs5U4RYvU2CmP9IaJToFUHo',
    appId: '1:906357683460:ios:54e4a78d76f4a59a9c0c51',
    messagingSenderId: '906357683460',
    projectId: 'road-companion-700b0',
    storageBucket: 'road-companion-700b0.firebasestorage.app',
    iosBundleId: 'com.example.roadCompanion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSDmBtqhitWs5U4RYvU2CmP9IaJToFUHo',
    appId: '1:906357683460:ios:54e4a78d76f4a59a9c0c51',
    messagingSenderId: '906357683460',
    projectId: 'road-companion-700b0',
    storageBucket: 'road-companion-700b0.firebasestorage.app',
    iosBundleId: 'com.example.roadCompanion',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALCe_6Isui2UfBTjGEwkzWdosHQcX_2Ls',
    appId: '1:906357683460:web:f2d5ca92911ea1fc9c0c51',
    messagingSenderId: '906357683460',
    projectId: 'road-companion-700b0',
    authDomain: 'road-companion-700b0.firebaseapp.com',
    storageBucket: 'road-companion-700b0.firebasestorage.app',
    measurementId: 'G-4JE72QZN53',
  );
}
